### ISSUE TITLE
How to set a fixed pixel position for the winner

### ISSUE THREAD

**Issue by Bp3289** [den-materials/assessment-2#2]
http://stackoverflow.com/questions/4081064/how-to-get-the-number-of-pixels-a-user-has-scrolled-down-the-page

http://stackoverflow.com/questions/8611145/race-conditions-with-javascript-event-handling

Troy helped a bit with tracking the position, but I'm having trouble storing the fixed position in a variable

**Comment by ZebGirouard** [comment]
We got it!  Nice work, Billy.
